#include "../Build.h"
#include "DummyTool/DummyTool.cpp"
#include "TriggerOutput/TriggerOutput.cpp"
#include "WCSimASCIReader/WCSimASCIReader.cpp"
#include "nhits/nhits.cpp"
#include "test_vertices/test_vertices.cpp"
#include "WCSimReader/WCSimReader.cpp"
#include "DataOut/DataOut.cpp"
#ifdef BONSAIEXISTS
#include "BONSAI/BONSAI.cpp"
#endif //BONSAIEXISTS
#include "ReconDataOut/ReconDataOut.cpp"
#include "dimfit/dimfit.cpp"
#include "ReconRandomiser/ReconRandomiser.cpp"
#include "ReconDataIn/ReconDataIn.cpp"
#include "pass_all/pass_all.cpp"

#include "ReconFilter/ReconFilter.cpp"
#include "ReconReset/ReconReset.cpp"
