#include "DummyTool/DummyTool.cpp"
#include "GPUProcessor/GPUProcessor.cpp"
#include "WCSim_ASCI_Reader/WCSim_ASCI_Reader.cpp"
#include "Trigger_Output/Trigger_Output.cpp"
#include "TriggerOutput/TriggerOutput.cpp"
#include "WCSimASCIReader/WCSimASCIReader.cpp"
